# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 046f0247efb934ae01341409e83e75ce074e78e5784a657d8ef74561434caa667f607048d08b337fb403bec10047670ad058bb94fbf2481a69b5afe390f24f55

test:
  secret_key_base: b12af062e008fd89fc4dfab3e6970401b27b9960f148f7652891244bad83b79f0c29b3f1424c104b75edbe66730eaa385ab2e609244749c65755b027066ef7d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
