# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ad64ecdc74b954ef12a88e74080bf422af9a755eb67d4b51bbd5d6a2b5c3d246e46014a99104430c9a01b2d24eb731186b1e45ca40a1b472babfd6e98780391

test:
  secret_key_base: 67ed9e100b9dbf1a920f9bffbdb7910a6bd3abc29ad266fca59c1e62b399893c24c2cd3b9419aa57486d71528a67234aaf953d99e261c0305edee5b8e2b83c92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
